GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/health HTTP/1.1

### Revenues
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/revenues HTTP/1.1
Authorization: Bearer 

### Invoices Count
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoices/count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGVmNzAwMmYzNGFjMWVlY2UxNzc2ZCIsImVtYWlsIjoibmV4dFR1dG9yaWFsQHRlc3QuY29tIiwibmFtZSI6Im5leHRUdXRvcmlhbCIsImlhdCI6MTczNzgzMDk2NX0.RxX5EpYa-pRlzYPDQot4GrX16vlfqpXBM63pQUdshLA

### Invoices
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoices HTTP/1.1
Authorization: Bearer 

### Invoices
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoice/6765bd4290a82bd45ae0b0bd HTTP/1.1
Authorization: Bearer  

### Invoices paginate
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoices/paginate HTTP/1.1
Authorization: Bearer 

### Invoices invoice-total-pages
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoices/page-count?q=bra HTTP/1.1
Authorization: Bearer 


### Customers
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/customer HTTP/1.1
Authorization: Bearer 

### Customers Count
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/customer/count HTTP/1.1
Authorization: Bearer 

### Status Count
GET https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/invoices/status-count HTTP/1.1
Authorization: Bearer 

### Register
POST https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "nextTutorial",
  "username": "nextTutorial",
  "email": "nextTutorial@test.com",
  "password": "123456"
}

### Login
POST https://backend-next-tutorial-fay6a.ondigitalocean.app/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "nextTutorial@test.com",
  "password": "123456"
}